### ISSUE TITLE
Issues while updating jobs on Jenkins (GET /crumbIssuer/api/json)

### ISSUE THREAD

**Issue by foeser** [crc83/gradle-jenkins-plugin#2]
Hey Serhi,

first of all thanks for maintain this plugin further down the road!

I tried to switch to your fork last week and ran into folder/null issue which you fixed with 1.4.7. The plugin is now able to get the config.xml from jenkins but an later request fails:

`15:33:57.999 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':Builder:Jenkins:updateJenkinsItems'.
[...]
15:33:58.326 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /job/Foobar-main-Compile-AllTargets-Win64/config.xml HTTP/1.1
15:33:59.645 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 200 OK
[...]
15:33:59.850 [WARN] [org.gradle.api.Task] Updating item Foobar-main-Compile-AllTargets-Win64 on http://jenkins/
15:33:59.855 [DEBUG] [groovyx.net.http.RESTClient] GET http://jenkins/crumbIssuer/api/json
15:33:59.855 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {}->http://jenkins
15:33:59.855 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Stale connection check
15:33:59.857 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
15:33:59.857 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] Cookie [version: 0][name: JSESSIONID.6971cf53][value: node0tqpp6u6a3i8a8szexldg1hk2355266.node0][domain: jenkins][path: /][expiry: null] match [jenkins:80/crumbIssuer/api/json]
15:33:59.858 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
15:33:59.858 [DEBUG] [org.apache.http.client.protocol.RequestTargetAuthentication] Target auth state: UNCHALLENGED
15:33:59.858 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
15:33:59.858 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
15:33:59.858 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /crumbIssuer/api/json HTTP/1.1
15:34:00.716 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 404 Not Found
15:34:00.717 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
15:34:00.717 [DEBUG] [groovyx.net.http.RESTClient] Response code: 404; found handler: org.codehaus.groovy.runtime.MethodClosure@1fb4377d
15:34:00.717 [DEBUG] [groovyx.net.http.RESTClient] Parsing response as: text/html
`

Would you mind to have a look please? :)

Thanks,
Florian

**Comment by crc83** [comment]
Could you please try jenkins url with port (like below) and tell me results?
`http://jenkins:80`

**Comment by foeser** [comment]
Hey Sergiy,

thanks for your fast reply. Result is the same:

`12:14:59.591 [WARN] [org.gradle.api.Task] Updating item Foobar-main-Compile-AllTargets-Win64 on http://jenkins:80/
12:14:59.595 [DEBUG] [groovyx.net.http.RESTClient] GET http://jenkins:80/crumbIssuer/api/json
12:14:59.595 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {}->http://jenkins:80
12:14:59.595 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Stale connection check
12:14:59.596 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
12:14:59.596 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] Cookie [version: 0][name: JSESSIONID.6971cf53][value: node01fysil6kr75uc1m43iezr30yy6356019.node0][domain: jenkins][path: /][expiry: null] match [jenkins:80/crumbIssuer/api/json]
12:14:59.596 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
12:14:59.596 [DEBUG] [org.apache.http.client.protocol.RequestTargetAuthentication] Target auth state: UNCHALLENGED
12:14:59.596 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
12:14:59.596 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
12:14:59.596 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /crumbIssuer/api/json HTTP/1.1
12:15:00.205 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 404 Not Found
12:15:00.205 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
12:15:00.205 [DEBUG] [groovyx.net.http.RESTClient] Response code: 404; found handler: org.codehaus.groovy.runtime.MethodClosure@f1b0658
12:15:00.206 [DEBUG] [groovyx.net.http.RESTClient] Parsing response as: text/html
`

**Comment by foeser** [comment]
Hey Sergiy,

I'm wondering if there are any news to it or if you might need more information?

Thanks again,
Florian

**Comment by crc83** [comment]
I had no time during last week so I plan to check it this week.
Meanwhile I'm trying to reproduce it with no success.

**Comment by crc83** [comment]
I'm getting 404 in case CSRF is disabled on jenkins.
Could you please confirm that you have CSRF disabled as well?

**Comment by foeser** [comment]
Hey,

thanks for your reply!

Yes CSRF is disabled on our end. It was always necessary to do so in order to update the jobs from the scripts.

https://github.com/ghale/gradle-jenkins-plugin/issues/78

It seems that its now reoccurring somehow.

Thanks in advance!

**Comment by crc83** [comment]
Hi. Finally I reproduced and found solution.
Please try to use version 1.4.8 and write me back your results.

**Comment by crc83** [comment]
Sorry. version 1.4.9

**Comment by foeser** [comment]
Hey,

it's working now :) Thanks a lot!
