### ISSUE TITLE
Update to Job DSL 1.68

### ISSUE THREAD

**Issue by foeser** [crc83/gradle-jenkins-plugin#3]
Hey,
I'm wondering if you have any plan to update to the latest Job DSL versions? :)

Thanks,
Florian

**Comment by crc83** [comment]
Hi,
At the first glance there I have to do minor changes to upgrade from 1.66 to 1.68.
However I'm not sure in tests there, because I removed integration tests during upgrade and have to recover them somehow.
Is this update urgent/important for You?

**Comment by foeser** [comment]
Hey,
no it's not super important for me, I was able to work around it.

I was interested in the sandbox mode for GroovySystemCommands (https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.step.SystemGroovyCommandContext.sandbox) but I can also approve the scripts in question by hand.

Thanks,
Florian

**Comment by crc83** [comment]
Well,
If You already have a solution, just submit pullrequest (with test if possible) and I do a release for you

**Comment by foeser** [comment]
Hey,
no you got me wrong sorry. Instead of using the sandbox mode for my groovy scripts I approve them within a Jenkins setting (https://jenkins.io/doc/book/managing/script-approval/). 

So I didn't change gradle-jenkins-plugin at all.
