### ISSUE TITLE
Official Fork?

### ISSUE THREAD

**Issue by ysb33r** [crc83/gradle-jenkins-plugin#4]
I would just like to have some clarity. Is this an official fork away from Gary's original plugin? DO you plan to merge back to that repo or simply go your own way?

I would help as one can know where to submit PRs to.

**Comment by crc83** [comment]
Hi,

As far as I know Gary doesn't maintain his plugin. So this is official
version.
Currently I maintain it to make my projects up and running. You may submit
PR's here.

Thank you
-Serhii


Вт, 10 лип. 2018 12:43 користувач Schalk W. Cronjé <notifications@github.com>
пише:

**Comment by ysb33r** [comment]
I would be willing to throw some energy behind this fork, if I know you'll have some time to get them reviewed and create new releases.
